export const CLOSE_MODAL = "CLOSE_MODAL";
export const SHOW_COMMENTS_FORM = "SHOW_COMMENTS_FORM";

export const NEWS_FETCH_REQUEST = "NEWS_FETCH_REQUEST";
export const NEWS_FETCH_SUCCESS = "NEWS_FETCH_SUCCESS";
export const NEWS_FETCH_FAILURE = "NEWS_FETCH_FAILURE";

export const SINGLENEWS_FETCH_REQUEST = "SINGLENEWS_FETCH_REQUEST";
export const SINGLENEWS_FETCH_SUCCESS = "SINGLENEWS_FETCH_SUCCESS";
export const SINGLENEWS_FETCH_FAILURE = "SINGLENEWS_FETCH_FAILURE";

export const NEWS_CREATE_FAILURE = "NEWS_CREATE_FAILURE";

export const NEWS_DELETE_FAILURE = "NEWS_DELETE_FAILURE";

export const COMMENT_FETCH_REQUEST = "COMMENT_FETCH_REQUEST";
export const COMMENT_FETCH_SUCCESS = "COMMENT_FETCH_SUCCESS";
export const COMMENT_FETCH_FAILURE = "COMMENT_FETCH_FAILURE";

export const COMMENT_CREATE_FAILURE = "COMMENT_CREATE_FAILURE";

export const COMMENT_DELETE_FAILURE = "COMMENT_DELETE_FAILURE";
